feat: bookings added
mrSkobelev/java-shareit pull request #3
Opened 2024-02-25 16:14 UTC by mrSkobelev

2024-02-26 15:57 UTC, avlin87 requested changes
Привет, Алексей,
Работа выглядит хорошо, автоматические проверки выполнились успешно, смотри, пожалуйста, комментарии ниже.

2024-02-26 15:57 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +            if (stateParam.equals(val.name())) {
`можно лучше`
Можно добавить stateParam.toUpperCase().equals() 
тем самым обезопасив код от нижнего регистра.

2024-02-26 15:57 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
>      WAITING, APPROVED, REJECTED, CANCELED;
`можно лучше`
Для улучшения читаемости кода принято располагать enum значения на отдельных строках.

2024-02-26 15:57 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +        return null;
`можно лучше`
По возможности стараться не возвращать null из методов.

2024-02-26 15:57 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +@Component
Хорошо бы стремиться к постоянству решений в коде.
BookingMapper - компонента Spring
а CommentMapper - использует статические методы.

Сделай, пожалуйста, все мапперы или компонентами или со статическими методами, чтобы было однообразие.

2024-02-26 15:57 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    //List<ItemInfoDto> getAllItems();
Закомментированный код лучше удалить.

2024-02-26 15:57 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    /*
Закомментированный код лучше всегда удалять.

2024-02-27 22:20 UTC, avlin87 requested changes
Привет, Алексей,
добавил комментариев, если есть возможность, пиши, пожалуйста, ответы в комментарии на github - "готово", "не согласен - потому что" и т.п.

2024-02-27 22:20 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    private final CommentMapper commentMapper = new CommentMapper();
CommentMapper у нас помечен аннотацией `@Component` - это значит, что Spring создаст объект этого класса и поместит его в свой контекст.
Spring инъекция может подставить нам нужный объект из контекста:
- нам не придется создавать его во всех местах, где такой объект нужен - Spring просто его подставит
- и это экономит память машины
- делает код чище

Инъекцию можно сделать через конструктор или через поле.
Рекомендуется пользоваться инъекцией через конструктор.
Чтобы не писать конструктор руками, можно поставит аннотацию на класс `@RequiredArgsConstructor` и она сгенерирует конструктор для приватных полей.

`private final CommentMapper commentMapper;`

2024-02-27 22:20 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    private final UserMapper userMapper = new UserMapper();
UserMapper и ItemMapper у нас помечены аннотацией `@Component` - это значит, что Spring создаст объект класса и поместит его в свой контекст.
Spring инъекция может подставить нам нужный объект из контекста:
- нам не придется создавать его во всех местах, где такой объект нужен - Spring просто его подставит
- и это экономит память машины
- делает код чище

Инъекцию можно сделать через конструктор или через поле.
Рекомендуется пользоваться инъекцией через конструктор.
Чтобы не писать конструктор руками, можно поставит аннотацию на класс `@RequiredArgsConstructor` и она сгенерирует конструктор для приватных полей.

`private final ItemMapper itemMapper;`
`private final UserMapper userMapper;`

2024-02-27 22:20 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +            if (stateParam.equals(val.name())) {
можешь добавить toUpperCase()

2024-02-27 22:57 UTC, mrSkobelev commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
>      WAITING, APPROVED, REJECTED, CANCELED;
Готово

2024-02-27 22:57 UTC, mrSkobelev commented on src/main/java/ru/practicum/shareit/booking/model/BookingState.java
> +            if (stateParam.equals(val.name())) {
Готово

2024-02-27 22:57 UTC, mrSkobelev commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +        return null;
Готово

2024-02-27 22:57 UTC, mrSkobelev commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    //List<ItemInfoDto> getAllItems();
Готово

2024-02-27 22:59 UTC, mrSkobelev commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    private final CommentMapper commentMapper = new CommentMapper();
Оууу, понял) Спасибо) 
Готово

2024-02-27 23:00 UTC, mrSkobelev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    private final UserMapper userMapper = new UserMapper();
Готово

2024-02-28 00:25 UTC, avlin87 approved these changes
Работу принимаю.

2024-03-01 13:58 UTC, merged